const first = document.querySelector("p.para");
console.log(first);
const second = document.querySelector("#second");
console.log(second);
const third = document.querySelector("#third");
console.log(third);
const fourth = document.querySelector("#fourth");
console.log(fourth);
const par = document.querySelectorAll("p");
console.log(par);
