<?php
$dbhost = "localhost";
$dbuser = "root";
$dbpass = "";
$dbname = "schoolpetal";


$con = new mysqli('localhost', 'root', '', 'schoolpetal');




if (!$con) {

 die(mysqli_error($con));
}



?>
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Login</title>
</head>
<body>
 
</body>
</html>